------------------- Tran 1
SET SESSION TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;
-- SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED;
-- SET SESSION TRANSACTION ISOLATION LEVEL REPEATABLE READ;
-- SET SESSION TRANSACTION ISOLATION LEVEL SERIALIZABLE;

SHOW VARIABLES LIKE 'tx_isolation';

START TRANSACTION;

SELECT id, name, date_of_birth FROM users where id = 11 order by  1 desc


Update users set name = 'STINGER Jones' where id = 11;

rollback 

commit 

------------------ Tran 2

SET SESSION TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;
-- SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED;
-- SET SESSION TRANSACTION ISOLATION LEVEL REPEATABLE READ;
-- SET SESSION TRANSACTION ISOLATION LEVEL SERIALIZABLE;

SHOW VARIABLES LIKE 'tx_isolation';

START TRANSACTION;

Update users set name = 'Merri Jones111' where id = 11;
INSERT INTO users VALUES (1005, '5555 555', '2000-01-01');


SELECT id, name, date_of_birth FROM users where id > 995 

SELECT id, name, date_of_birth
FROM mydb.users
where id = 11;

COMMIT

rollback